version: "3.8"

services:
  db:
    image: postgres:15
    container_name: uzairvays_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abudev99
      POSTGRES_DB: airways
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: uzairvays_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run start:prod

volumes:
  postgres_data:
